### PR TITLE
complete project

### PR DESCRIPTION
**Pull request by GaelTikeng**

### CODE REVIEW

**Comment by kivenalaric** [comment]
Pay attention to details, that's just what is lacking in your project. its good.

**Comment by kivenalaric** [comment]
Also, use the right viewpoint width. media query for mobile should start at 600px

**Review by nganifaith — APPROVED** [review]
great job @GaelTikeng . 🥁🥁🥁🥁🥁💃🏼🥁💃🏼🥁👯👯👯 **Project approve** You can go ahead and merge your work.

**Pull request merged**
